name: Integration

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
      - name: Test (integration)
        env:
          MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}
          MP_BASE_URL: ${{ secrets.MP_BASE_URL }}
        run: go test ./... -tags=integration -v
